### ISSUE TITLE
Idea: could ´std::tuple´ and ´std::bitset´ be used for more efficient synchronizable data storage?

### ISSUE THREAD

**Issue by SuperV1234** [binary1248/SFNUL#3]
I'm a big fan of how easy to use your library is and wanted to share some thoughts about possible optimizations. 

Instead of binding synchronizable fields at runtime, would it be possible to generate them at compile time using ´std::tuple´ and C++11 variadic templates?

I was thinking about something like this:

    class Player : public SerializableObject<
        int, // x
        int, // y
        float, // health
        std::string // name
    >
    {
        ...
    }

    // The above struct would generate something like:

    class Player
    {
        std::bitset<4> dirtyFlags;
        std::tuple<int, int, float, std::string> fields;

        template<int I> void setAt(const typeAt<I>& x)
        {
            std::get<I>(fields) = x;
            dirtyFlags[I] = true;
        }

        ...
    }

Generating the data structure wouldn't be too difficult. Do you, however, think that serializing and synchronizing structures generated that way would be possible?

**Comment by binary1248** [comment]
Implemented in df1bb122824ca8d751903bf6cd753c53ecda3e7c.

It's not _exactly_ what you suggested, but I think the core idea is the same. `std::tuple` can now be used in `sfn::SyncedType` and will make use of a single dirty flag just like any other type. This fits nicely into the philosophy behind SyncedType/SyncedObject without having to introduce new concepts into the library.

After a lot of tinkering, I came to the conclusion that adding flags for each element using a `std::bitset` wouldn't really add much in terms of usability or performance. The current flag is also only used as an optimization instead of a necessity.

You will be able to access the tuple elements using `std::get` on the _contained value_ itself, which you can retrieve via `.GetValue()` or `.Get()` depending on whether you want a const or non-const reference to work with. It should be sufficiently demonstrated in the Synchronization example.

If you have any further suggestions, I'd be happy to hear them. :wink:
